language: node_js

cache:
  directories:
    - node_modules
    - ~/.npm

node_js:
  - "14"

git:
  depth: 3

script:
  - npm install netlify-cli -g
  - npm run build
  - netlify deploy --prod --dir=dist